services:
  djangoapp:
    build:
      context: .
    container_name: inpc_djangoapp
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      inpc_mydb:
        condition: service_healthy
    environment:
      - DJANGO_SETTINGS_MODULE=inpc_project.settings
      - DB_HOST=inpc_mydb
      - DB_PORT=3307
      - DB_NAME=inpc_db
      - DB_USER=root
      - DB_PASSWORD=Medlemin23014

  inpc_mydb:
    image: mysql:8.0
    container_name: inpc_mydb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Medlemin23014
      MYSQL_DATABASE: inpc_db
    ports:
      - "127.0.0.1:33307:3307"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --port=3307 --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pMedlemin23014"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mysql_data: