version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: inpc_mysql
    environment:
      MYSQL_ROOT_PASSWORD: Medlemin23014
      MYSQL_DATABASE: inpc_db
    ports:
      - "24014:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --sql_mode=STRICT_TRANS_TABLES

  djangoapp:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: inpc_django
    command: python manage.py runserver 0.0.0.0:23014
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "23014:23014"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=inpc_project.settings
      - DB_NAME=inpc_db
      - DB_USER=root
      - DB_PASSWORD=Medlemin23014
      - DATABASE_HOST=db
      - DATABASE_PORT=3306

volumes:
  mysql_data:
  static_volume: