# Generated by Django 4.2.9 on 2025-01-30 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inpc_core', '0002_cart_cartproduct_commune_moughataa_pointofsale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_products', to='inpc_core.cart'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_products', to='inpc_core.product'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='moughataa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commune_set', to='inpc_core.moughataa'),
        ),
        migrations.AlterField(
            model_name='moughataa',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moughataa_set', to='inpc_core.wilaya'),
        ),
        migrations.AlterField(
            model_name='pointofsale',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_of_sale', to='inpc_core.commune'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inpc_core.producttype'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='point_of_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='inpc_core.pointofsale'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='inpc_core.product'),
        ),
    ]
